// SARTHI Admin Data Service
// Domain model and seed telemetry for SARTHI National Meteorological LMS Administration.

export const initialAdminProfile = {
  id: "admin-mukul-pandey",
  name: "Mukul Pandey",
  role: "ADMIN",
  title: "National Project Director & Lead Administrator",
  organization: "SARTHI - India Meteorological Department (MoES)",
  email: "admin.demo@imd.gov.in",
  avatar: "/images/student-img-2.jpg",
  joinedDate: "2024-01-15",
  permissions: ["ALL_ACCESS", "USER_MANAGEMENT", "FINANCE", "COURSE_PUBLISH", "SYSTEM_SETTINGS"],
};

export const initialAdminStats = {
  totalRevenue: 0,
  revenueFormatted: "₹0",
  revenueGrowth: "↓ 0% Growth",
  trainingBudget: "₹24,80,000",
  totalStudents: 142,
  studentsSubtitle: "● 142 Registered Learners",
  studentsGrowth: "+18% this month",
  publishedCourses: 10,
  coursesSubtitle: "● Course Catalog",
  coursesPending: 1,
  pendingApprovals: 1,
  approvalsSubtitle: "ACTION REQUIRED",
};

// Revenue & Training Analytics Chart Data
// Matches the curve in the screenshot: Mon starts around ~20k, slight dip Wed, rises Fri-Sat to peak ~45k, slight taper Sun
export const initialRevenueChartData = {
  week: [
    { day: "Mon", revenue: 19500, students: 18 },
    { day: "Tue", revenue: 24200, students: 25 },
    { day: "Wed", revenue: 20800, students: 20 },
    { day: "Thu", revenue: 31500, students: 34 },
    { day: "Fri", revenue: 33200, students: 38 },
    { day: "Sat", revenue: 47800, students: 52 },
    { day: "Sun", revenue: 42100, students: 44 },
  ],
  month: [
    { day: "Jan", revenue: 185000, students: 95 },
    { day: "Feb", revenue: 245000, students: 110 },
    { day: "Mar", revenue: 310000, students: 128 },
    { day: "Apr", revenue: 290000, students: 135 },
    { day: "May", revenue: 385000, students: 142 },
    { day: "Jun", revenue: 440000, students: 160 },
  ],
};

// Admin Insights (Matching reference screenshot tabs: Alerts (4) & Growth (3))
export const initialAdminInsights = {
  alerts: [
    {
      id: "alt-1",
      title: "Course Bundling & Career Track Upsells",
      badge: "HIGH",
      badgeType: "high",
      description: "Bundle Satellite Remote Sensing + NWP Modeling into a single Certified Operational Meteorologist Track to boost completion velocity.",
      metricLabel: "Target AOV",
      metricValue: "+25% Growth",
    },
    {
      id: "alt-2",
      title: "Automated Student Re-engagement",
      badge: "MED",
      badgeType: "med",
      description: "Trigger SMS and email prompts for trainees inactive for >5 days to improve module completion rates across Radar divisions.",
      metricLabel: "Completion",
      metricValue: "+35% Retention",
    },
    {
      id: "alt-3",
      title: "Live Radar Stream High Concurrency",
      badge: "HIGH",
      badgeType: "high",
      description: "Peak concurrency anticipated during tomorrow's pre-monsoon squall line masterclass. Allocate additional edge worker nodes.",
      metricLabel: "Concurrency",
      metricValue: "98.8% Uptime",
    },
    {
      id: "alt-4",
      title: "Pending Faculty Accreditation Sign-off",
      badge: "ACTION",
      badgeType: "med",
      description: "1 new curriculum module by Dr. Sunita Deshmukh (Climate Trend Analytics) is awaiting administrative approval.",
      metricLabel: "Action",
      metricValue: "1 Pending",
    },
  ],
  growth: [
    {
      id: "gro-1",
      title: "Inter-Divisional Cross-Skilling",
      badge: "GROWTH",
      badgeType: "growth",
      description: "Aviation weather forecasters showing 88% interest in Doppler Radar nowcast modules.",
      metricLabel: "Enrollment",
      metricValue: "+42% Trainees",
    },
    {
      id: "gro-2",
      title: "MoES Digital Capacity Grant Allocation",
      badge: "FINANCE",
      badgeType: "growth",
      description: "FY 2026-27 infrastructure grant approved for high-throughput meteorological workstation licenses.",
      metricLabel: "Grant",
      metricValue: "₹15.2 Lakhs",
    },
    {
      id: "gro-3",
      title: "Certification Verification Index",
      badge: "INTEGRITY",
      badgeType: "growth",
      description: "100% of issued trainee certificates now digitally signed and verifiable via QR code on national portal.",
      metricLabel: "Integrity",
      metricValue: "100% Valid",
    },
  ],
};

// Users Directory (Trainees, Trainers, Administrators)
export const initialAdminUsers = [
  {
    id: "usr-1",
    name: "Mohit Raj",
    email: "student.demo@imd.gov.in",
    role: "TRAINEE",
    division: "NWP Modeling Division",
    enrolledCourses: 4,
    status: "ACTIVE",
    joinedDate: "2025-08-12",
    lastLogin: "10 mins ago",
    avatar: "/images/student-img-1.jpg",
  },
  {
    id: "usr-2",
    name: "Dr. R. K. Sharma",
    email: "rk.sharma@imd.gov.in",
    role: "FACULTY",
    division: "Satellite Meteorology Division",
    enrolledCourses: 4,
    status: "ACTIVE",
    joinedDate: "2024-03-01",
    lastLogin: "25 mins ago",
    avatar: "/images/student-img-1.jpg",
  },
  {
    id: "usr-3",
    name: "Priya Sharma",
    email: "priya.sharma@imd.gov.in",
    role: "TRAINEE",
    division: "Satellite Meteorology Division",
    enrolledCourses: 2,
    status: "ACTIVE",
    joinedDate: "2025-09-01",
    lastLogin: "1 hour ago",
    avatar: "/images/student-img-2.jpg",
  },
  {
    id: "usr-4",
    name: "Rahul Verma",
    email: "rahul.verma@imd.gov.in",
    role: "TRAINEE",
    division: "Radar Operations (DWR Pune)",
    enrolledCourses: 2,
    status: "ACTIVE",
    joinedDate: "2025-09-15",
    lastLogin: "3 hours ago",
    avatar: "/images/student-img-3.jpg",
  },
  {
    id: "usr-5",
    name: "Vikram Malhotra",
    email: "vikram.m@imd.gov.in",
    role: "TRAINEE",
    division: "Cyclone Warning Division",
    enrolledCourses: 3,
    status: "ACTIVE",
    joinedDate: "2025-07-20",
    lastLogin: "30 mins ago",
    avatar: "/images/student-img-1.jpg",
  },
  {
    id: "usr-6",
    name: "Dr. Sunita Deshmukh",
    email: "sunita.d@imd.gov.in",
    role: "FACULTY",
    division: "Monsoon Forecasting Center (Pune)",
    enrolledCourses: 1,
    status: "ACTIVE",
    joinedDate: "2024-06-10",
    lastLogin: "5 hours ago",
    avatar: "/images/student-img-2.jpg",
  },
  {
    id: "usr-7",
    name: "Deepak Choudhury",
    email: "deepak.c@imd.gov.in",
    role: "TRAINEE",
    division: "Aviation Weather (IGI Airport)",
    enrolledCourses: 1,
    status: "PENDING_REVIEW",
    joinedDate: "2025-10-02",
    lastLogin: "1 day ago",
    avatar: "/images/student-img-3.jpg",
  },
  {
    id: "usr-8",
    name: "Mukul Pandey",
    email: "admin.demo@imd.gov.in",
    role: "ADMIN",
    division: "HQ Directorate, New Delhi",
    enrolledCourses: 10,
    status: "ACTIVE",
    joinedDate: "2024-01-15",
    lastLogin: "Online Now",
    avatar: "/images/student-img-2.jpg",
  },
];

// Published & Pending Courses
export const initialAdminCourses = [
  {
    id: "crs-1",
    title: "Satellite Meteorology & Remote Sensing",
    category: "Remote Sensing",
    instructor: "Dr. R. K. Sharma (Scientist-F)",
    enrolled: 68,
    completionRate: "72%",
    status: "PUBLISHED",
    dateAdded: "2025-06-15",
    price: "₹0 (Govt Subsidized)",
  },
  {
    id: "crs-2",
    title: "Numerical Weather Prediction (NWP) Modeling",
    category: "Atmospheric Modeling",
    instructor: "Prof. S. N. Mukherjee",
    enrolled: 52,
    completionRate: "88%",
    status: "PUBLISHED",
    dateAdded: "2025-07-01",
    price: "₹0 (Govt Subsidized)",
  },
  {
    id: "crs-3",
    title: "Doppler Weather Radar (DWR) & Severe Storms",
    category: "Radar Meteorology",
    instructor: "Dr. Ananya Verma",
    enrolled: 42,
    completionRate: "64%",
    status: "PUBLISHED",
    dateAdded: "2025-08-10",
    price: "₹0 (Govt Subsidized)",
  },
  {
    id: "crs-4",
    title: "Monsoon Synoptic Forecasting & Climate Trends",
    category: "Climatology",
    instructor: "Dr. Sunita Deshmukh",
    enrolled: 24,
    completionRate: "45%",
    status: "PENDING_APPROVAL", // This is the 1 pending approval shown in the screenshot!
    dateAdded: "2026-03-01",
    price: "₹0 (Govt Subsidized)",
  },
];

// Live Operations Telemetry
export const initialLiveOperations = {
  serverStatus: "HEALTHY",
  uptime: "99.98%",
  activeSessionsCount: 48,
  activeLiveRoomsCount: 2,
  cpuUtilization: "34%",
  memoryUsage: "4.2 GB / 16 GB",
  databaseLatencyMs: "18ms",
  websocketConnected: 62,
  cacheHitRatio: "96.4%",
  activeRooms: [
    {
      id: "room-1",
      topic: "INSAT-3DR Rapid Scan & Convective Cell Tracking",
      instructor: "Dr. R. K. Sharma",
      connectedLearners: 32,
      duration: "00:48:22",
      status: "STREAMING",
    },
    {
      id: "room-2",
      topic: "WRF-DA 3D-Var Data Assimilation Hands-on",
      instructor: "Prof. S. N. Mukherjee",
      connectedLearners: 16,
      duration: "00:22:15",
      status: "STREAMING",
    },
  ],
};

// Email Broadcast Logs & Templates
export const initialEmailLogs = [
  {
    id: "em-1",
    subject: "SARTHI Platform Update: Live Radar Studio Now Operational",
    recipientsCount: 186,
    sentAt: "2026-03-05 10:00 IST",
    sender: "mukul.pandey@imd.gov.in",
    status: "DELIVERED",
    openRate: "89.4%",
  },
  {
    id: "em-2",
    subject: "Notice: Mandatory Pre-Monsoon Training Assessment Schedule",
    recipientsCount: 142,
    sentAt: "2026-03-01 14:30 IST",
    sender: "admin.director@imd.gov.in",
    status: "DELIVERED",
    openRate: "94.2%",
  },
];
